# Generated by Django 5.0.5 on 2024-07-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='queue_message', to='message.driverorder'),
        ),
    ]
