# Generated by Django 5.0.5 on 2024-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='drivers',
            field=models.ManyToManyField(default=[], related_name='queue_message', to='message.driverorder'),
        ),
    ]
