# Generated by Django 5.0.5 on 2024-07-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_drivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(unique=True),
        ),
    ]
