# Generated by Django 5.0.5 on 2024-07-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_sendmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='chat_id',
            field=models.CharField(max_length=255),
        ),
    ]
