# Generated by Django 5.0.5 on 2024-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_sendmessage_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='voice',
            field=models.BooleanField(default=False),
        ),
    ]
