name: driver
version: "3.12"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: ikromov0303
       POSTGRES_DB: postgres
       POSTGRES_HOST_AUTH_METHOD: scram-sha-256
       POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    container_name: backend
    image: backend
    build: .
    restart: always
    volumes:
      - .static:/static_files
    ports:
      - "8000:8000"


volumes:
  postgres_data: