# Generated by Django 5.1.2 on 2024-10-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_id', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'GET_MESSAGE'), (2, 'SEND_MESSAGE')])),
            ],
        ),
    ]
