# Generated by Django 5.0.6 on 2024-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.IntegerField(choices=[(1, 'Get Message'), (2, 'Send Message')], default=1),
            preserve_default=False,
        ),
    ]
