# Generated by Django 5.0.5 on 2024-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.IntegerField(choices=[(1, 'GET_MESSAGE'), (2, 'SEND_MESSAGE')]),
        ),
    ]
