# Generated by Django 5.0.5 on 2024-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='telegram_id',
            field=models.CharField(max_length=255),
        ),
    ]
