# Generated by Django 5.1.2 on 2024-10-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.TextField(max_length=200)),
                ('chat_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'DRIVER'), (3, 'SIMPLE')], default=3)),
            ],
            options={
                'indexes': [models.Index(fields=['telegram_id'], name='user_user_telegra_7027db_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.TextField(max_length=200)),
                ('step', models.CharField(max_length=200)),
                ('step_under', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['telegram_id'], name='user_userst_telegra_ac25ba_idx')],
            },
        ),
    ]
