# Generated by Django 5.1.3 on 2025-01-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStage',
        ),
        migrations.AddField(
            model_name='user',
            name='step',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='step_under',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
