# Generated by Django 5.0.6 on 2024-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_telegram_username_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.TextField(unique=True),
        ),
    ]
