# Generated by Django 5.0.5 on 2024-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userstage_alter_user_telegram_id_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'DRIVER'), (3, 'SIMPLE')], default=3),
        ),
    ]
