# Generated by Django 5.0.5 on 2024-07-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(default=12, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
